#!/bin/sh

export STAT_MSG_SAVED="Belutexted - Currently saved - CTRL + H to help"

export STAT_MSG_UNSAVED="Belutexted - Currently NOT saved - CTRL + H to help"

export TAB_WIDTH=4


# for paranthesis colors, ANSI escapement color codes. for no colors, just f as:
#export PARANTHESES_COLOR="f"
export PARANTHESES_COLOR="31" #red paranthesis, for example.

#export HASH_COLOR="f" #these with f are for colorless.
export HASH_COLOR="45" #magenta background for hash.

#export SINGLE_QUOTE_COLOR="f"
export SINGLE_QUOTE_COLOR="92" #light green for single quote.

#export DOUBLE_QUOTE_COLOR="f"
export DOUBLE_QUOTE_COLOR="32" #green for double quote.

#export OPERATORS_COMP_SIGN_COLOR="f"
export OPERATORS_COMP_SIGN_COLOR="96" #light magenta for comparison signs and operators.

#export AMPERSAND_COLOR="f"
export AMPERSAND_AT_DOLLAR_COLOR="95" #bright magenta for &, @, $ and ?.

#export SQUARE_BRACKETS_COLOR="f"
export SQUARE_BRACKETS_COLOR="93" #bright yellow for square brackets.

#export CURLY_BRACES_COLOR="f"
export CURLY_BRACES_COLOR="35" #magenta for curly braces.

#export BACKSLASH_COLOR="f"
export BACKSLASH_COLOR="44" #blue background for backslash

#export PUNCTUATION_COLOR="f"
export PUNCTUATION_COLOR="36" #cyan for punctuation (, . ; :)

# execute binary
exec ./bed "$@"
